import { createClient } from '@supabase/supabase-js';

export const FRAME_PIPELINE_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COLORIZED: 'colorized',
  NEEDS_REVIEW: 'needs_review_not_reference',
  CORRECTING: 'correcting',
  CORRECTION_APPLIED: 'correction_applied',
  CORRECTION_KEYFRAME: 'correction_keyframe',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export const JOB_STATUS = {
  CREATED: 'created',
  RUNNING: 'running',
  WAITING_REVIEW: 'waiting_review',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    throw new Error('Missing SUPABASE_URL/VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  }

  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export function sendJson(res, status, payload) {
  res.statusCode = status;
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Cache-Control', 'no-store');
  res.end(JSON.stringify(payload));
}

export function sendError(res, status, message, details = null) {
  sendJson(res, status, {
    ok: false,
    error: message,
    details,
  });
}

export async function readJsonBody(req) {
  if (req.body && typeof req.body === 'object') return req.body;

  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString('utf8');
  if (!raw) return {};

  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error('Invalid JSON body');
  }
}

export function ensureMethod(req, res, allowed) {
  if (!allowed.includes(req.method)) {
    res.setHeader('Allow', allowed.join(', '));
    sendError(res, 405, `Method ${req.method} not allowed`);
    return false;
  }
  return true;
}

export async function getLatestJob(supabase, projectId, jobId = null) {
  let query = supabase
    .from('colorization_jobs')
    .select('*')
    .eq('project_id', projectId);

  if (jobId) {
    query = query.eq('id', jobId).single();
  } else {
    query = query.order('created_at', { ascending: false }).limit(1).maybeSingle();
  }

  const { data, error } = await query;
  if (error) throw error;
  return data;
}

export async function getProjectFrames(supabase, projectId) {
  const { data, error } = await supabase
    .from('frames')
    .select('*')
    .eq('project_id', projectId)
    .order('frame_index', { ascending: true });

  if (error) throw error;
  return data || [];
}

export async function getJobFrames(supabase, jobId) {
  const { data, error } = await supabase
    .from('colorization_job_frames')
    .select('*')
    .eq('job_id', jobId)
    .order('frame_index', { ascending: true });

  if (error) throw error;
  return data || [];
}

export function buildMockSegments(frameIndex = 0) {
  // First integration fallback: deterministic segment candidates.
  // Later replace this with real segment_ids/segments_json generated by CV backend.
  return [
    {
      segment_id: 1,
      role_guess: 'skin',
      suggested_color: '#F2B08C',
      confidence: 0.62,
      reason: 'Low-confidence center/face-like region fallback',
    },
    {
      segment_id: 2,
      role_guess: 'hair',
      suggested_color: '#1E293B',
      confidence: 0.58,
      reason: 'Low-confidence upper-region fallback',
    },
    {
      segment_id: 3,
      role_guess: 'shirt',
      suggested_color: frameIndex % 2 === 0 ? '#3B82F6' : '#8B5CF6',
      confidence: 0.55,
      reason: 'Low-confidence clothing-like region fallback',
    },
    {
      segment_id: 4,
      role_guess: 'background',
      suggested_color: '#E5E7EB',
      confidence: 0.7,
      reason: 'Background/fill fallback',
    },
  ];
}

export function defaultRolePalette(roleMemory = []) {
  const memoryColors = roleMemory
    .map((row) => row.locked_color)
    .filter(Boolean);

  const fallback = [
    '#F2B08C',
    '#1E293B',
    '#3B82F6',
    '#8B5CF6',
    '#10B981',
    '#F59E0B',
    '#EF4444',
    '#E5E7EB',
  ];

  return Array.from(new Set([...memoryColors, ...fallback])).slice(0, 12);
}

export function normalizeCorrectionList(body) {
  const corrections = Array.isArray(body.corrections)
    ? body.corrections
    : [
        {
          segment_id: body.segment_id,
          role_id: body.role_id || body.role,
          color_hex: body.color_hex,
          palette_locked: body.palette_locked,
          source: body.source || body.correction_source,
        },
      ];

  return corrections
    .filter((item) => item && item.segment_id !== undefined && item.color_hex)
    .map((item) => ({
      segment_id: Number(item.segment_id),
      role_id: item.role_id || 'unknown',
      color_hex: item.color_hex,
      palette_locked: item.palette_locked !== false,
      source: item.source || 'user_manual',
      confidence: item.confidence ?? 1.0,
      metadata: item.metadata || {},
    }));
}

// -----------------------------
// Real CV service integration
// -----------------------------

export const CV_ENGINE_STATUS = {
  COLORIZED: 'colorized',
  NEEDS_REVIEW: 'needs_review_not_reference',
};

export function getCvServiceConfig() {
  const baseUrl = String(process.env.FRAMEFLOW_CV_API_URL || process.env.CV_API_URL || '').trim();
  const apiKey = String(process.env.FRAMEFLOW_CV_API_KEY || process.env.CV_API_KEY || '').trim();

  if (!baseUrl) {
    throw new Error('Missing FRAMEFLOW_CV_API_URL. Deploy backend_cv first, then set this env in Vercel.');
  }

  return {
    baseUrl: baseUrl.replace(/\/$/, ''),
    apiKey,
  };
}

export async function callCvService(path, payload) {
  const { baseUrl, apiKey } = getCvServiceConfig();

  const response = await fetch(`${baseUrl}${path}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(apiKey ? { 'x-frameflow-key': apiKey } : {}),
    },
    body: JSON.stringify(payload),
  });

  const data = await response.json().catch(() => null);

  if (!response.ok || data?.ok === false) {
    throw new Error(data?.detail || data?.error || `CV service failed: ${response.status}`);
  }

  return data;
}

export function sanitizePathPart(value) {
  return String(value || 'asset')
    .replace(/[^a-zA-Z0-9._-]/g, '_')
    .slice(0, 120);
}

export function base64ToBuffer(base64) {
  return Buffer.from(String(base64 || ''), 'base64');
}

export async function uploadBase64Asset(supabase, { bucket, path, base64, contentType = 'image/png' }) {
  const body = base64ToBuffer(base64);
  const { error } = await supabase.storage
    .from(bucket)
    .upload(path, body, {
      contentType,
      upsert: true,
    });

  if (error) throw error;

  const { data } = supabase.storage.from(bucket).getPublicUrl(path);
  return data.publicUrl;
}

export async function getRoleMemory(supabase, projectId) {
  const { data, error } = await supabase
    .from('role_memory')
    .select('role_id,locked_color,source_segment_id,priority,is_locked')
    .eq('project_id', projectId)
    .order('priority', { ascending: false });

  if (error) throw error;
  return data || [];
}

export async function getFrameById(supabase, frameId) {
  if (!frameId) return null;
  const { data, error } = await supabase
    .from('frames')
    .select('*')
    .eq('id', frameId)
    .maybeSingle();

  if (error) throw error;
  return data;
}

export function buildCvSettings(jobSettings = {}) {
  return {
    line_threshold: Number(jobSettings.line_threshold ?? 180),
    adaptive_threshold: jobSettings.adaptive_threshold !== false,
    gap_close_kernel: Number(jobSettings.gap_close_kernel ?? 3),
    gap_close_iterations: Number(jobSettings.gap_close_iterations ?? 1),
    line_dilate: Number(jobSettings.line_dilate ?? 1),
    min_segment_area: Number(jobSettings.min_segment_area ?? 25),
    max_side: Number(jobSettings.max_side ?? 0),
    low_confidence_threshold: Number(jobSettings.low_confidence_threshold ?? 0.55),
    flow_min_ratio: Number(jobSettings.flow_min_ratio ?? 0.16),
    use_flow: jobSettings.use_flow !== false,
    line_mode: jobSettings.line_mode || 'original',
    max_low_confidence: Number(jobSettings.max_low_confidence ?? 20),
    min_review_area: Number(jobSettings.min_review_area ?? 120),
    min_review_area_ratio: Number(jobSettings.min_review_area_ratio ?? 0.0005),
    use_role_memory: jobSettings.use_role_memory !== false,
    role_memory_override_max_confidence: Number(jobSettings.role_memory_override_max_confidence ?? 0.82),
  };
}

export function buildAssetPaths({ projectId, jobId, frameId, frameIndex, frameName }) {
  const safeProject = sanitizePathPart(projectId);
  const safeJob = sanitizePathPart(jobId || 'job');
  const safeFrame = sanitizePathPart(frameId);
  const safeName = sanitizePathPart(frameName || `frame_${frameIndex}`);
  const stem = safeName.replace(/\.[^.]+$/, '');
  const prefix = `${safeProject}/colorization/${safeJob}/${String(frameIndex).padStart(4, '0')}_${safeFrame}_${stem}`;

  return {
    colorized: `${prefix}_colorized.png`,
    overlay: `${prefix}_low_confidence_overlay.png`,
    segmentIds: `${prefix}_segment_ids.png`,
    encodedSegmentMap: `${prefix}_encoded_segment_map.png`,
    segmentsJson: `${prefix}_segments.json`,
  };
}
