import { createClient } from '@supabase/supabase-js';

export const FRAME_PIPELINE_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COLORIZED: 'colorized',
  NEEDS_REVIEW: 'needs_review_not_reference',
  CORRECTING: 'correcting',
  CORRECTION_APPLIED: 'correction_applied',
  CORRECTION_KEYFRAME: 'correction_keyframe',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export const JOB_STATUS = {
  CREATED: 'created',
  RUNNING: 'running',
  WAITING_REVIEW: 'waiting_review',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

export function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    throw new Error('Missing SUPABASE_URL/VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  }

  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export function sendJson(res, status, payload) {
  res.statusCode = status;
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Cache-Control', 'no-store');
  res.end(JSON.stringify(payload));
}

export function sendError(res, status, message, details = null) {
  sendJson(res, status, {
    ok: false,
    error: message,
    details,
  });
}

export async function readJsonBody(req) {
  if (req.body && typeof req.body === 'object') return req.body;

  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString('utf8');
  if (!raw) return {};

  try {
    return JSON.parse(raw);
  } catch (error) {
    throw new Error('Invalid JSON body');
  }
}

export function ensureMethod(req, res, allowed) {
  if (!allowed.includes(req.method)) {
    res.setHeader('Allow', allowed.join(', '));
    sendError(res, 405, `Method ${req.method} not allowed`);
    return false;
  }
  return true;
}

export async function getLatestJob(supabase, projectId, jobId = null) {
  let query = supabase
    .from('colorization_jobs')
    .select('*')
    .eq('project_id', projectId);

  if (jobId) {
    query = query.eq('id', jobId).single();
  } else {
    query = query.order('created_at', { ascending: false }).limit(1).maybeSingle();
  }

  const { data, error } = await query;
  if (error) throw error;
  return data;
}

export async function getProjectFrames(supabase, projectId) {
  const { data, error } = await supabase
    .from('frames')
    .select('*')
    .eq('project_id', projectId)
    .order('frame_index', { ascending: true });

  if (error) throw error;
  return data || [];
}

export async function getJobFrames(supabase, jobId) {
  const { data, error } = await supabase
    .from('colorization_job_frames')
    .select('*')
    .eq('job_id', jobId)
    .order('frame_index', { ascending: true });

  if (error) throw error;
  return data || [];
}

export function buildMockSegments(frameIndex = 0) {
  // First integration fallback: deterministic segment candidates.
  // Later replace this with real segment_ids/segments_json generated by CV backend.
  return [
    {
      segment_id: 1,
      role_guess: 'skin',
      suggested_color: '#F2B08C',
      confidence: 0.62,
      reason: 'Low-confidence center/face-like region fallback',
    },
    {
      segment_id: 2,
      role_guess: 'hair',
      suggested_color: '#1E293B',
      confidence: 0.58,
      reason: 'Low-confidence upper-region fallback',
    },
    {
      segment_id: 3,
      role_guess: 'shirt',
      suggested_color: frameIndex % 2 === 0 ? '#3B82F6' : '#8B5CF6',
      confidence: 0.55,
      reason: 'Low-confidence clothing-like region fallback',
    },
    {
      segment_id: 4,
      role_guess: 'background',
      suggested_color: '#E5E7EB',
      confidence: 0.7,
      reason: 'Background/fill fallback',
    },
  ];
}

export function defaultRolePalette(roleMemory = []) {
  const memoryColors = roleMemory
    .map((row) => row.locked_color)
    .filter(Boolean);

  const fallback = [
    '#F2B08C',
    '#1E293B',
    '#3B82F6',
    '#8B5CF6',
    '#10B981',
    '#F59E0B',
    '#EF4444',
    '#E5E7EB',
  ];

  return Array.from(new Set([...memoryColors, ...fallback])).slice(0, 12);
}

export function normalizeCorrectionList(body) {
  const corrections = Array.isArray(body.corrections)
    ? body.corrections
    : [
        {
          segment_id: body.segment_id,
          role_id: body.role_id || body.role,
          color_hex: body.color_hex,
          palette_locked: body.palette_locked,
          source: body.source || body.correction_source,
        },
      ];

  return corrections
    .filter((item) => item && item.segment_id !== undefined && item.color_hex)
    .map((item) => ({
      segment_id: Number(item.segment_id),
      role_id: item.role_id || 'unknown',
      color_hex: item.color_hex,
      palette_locked: item.palette_locked !== false,
      source: item.source || 'user_manual',
      confidence: item.confidence ?? 1.0,
      metadata: item.metadata || {},
    }));
}
